services:
  aws:
    build:
      context: .
      dockerfile: Dockerfile.aws
    volumes:
      - .aws:/root/.aws
      - ./terraform:/terraform
  ansible:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    volumes:
      - ./terraform:/terraform
      - ./app:/app